archives:
  - format: binary
builds:
- binary: '{{ .ProjectName }}'
  env:
    - CGO_ENABLED=0
dockers:
- image_templates:
  - "ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-amd64"
  use: buildx
  goarch: amd64
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  build_flag_templates:
  - "--platform=linux/arm64/v8"
- image_templates:
  - "ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-armv7"
  use: buildx
  goarch: arm
  goarm: "7"
  build_flag_templates:
  - "--platform=linux/arm/v7"
- image_templates:
  - "ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-armv6"
  use: buildx
  goarch: arm
  goarm: "6"
  build_flag_templates:
  - "--platform=linux/arm/v6"
docker_manifests:
- name_template: ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-armv7
  - ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-armv6
- name_template: ghcr.io/fogninid/{{ .ProjectName }}:v{{ .Major }}
  image_templates:
  - ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-armv7
  - ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-armv6
- name_template: ghcr.io/fogninid/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-armv7
  - ghcr.io/fogninid/{{ .ProjectName }}:{{ .Version }}-armv6
